# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext


# here we defined the hierarci between the ROLE
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATEUR]
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user: {password: userpassword, roles: [ROLE_USER]}
     #   main:
     #       entity:
     #           class:    UserBundle:User
     #           property: username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     /

    access_control: