app_homepage:
    path:    /
    defaults:
        _controller: AppBundle:Site:index

#Account routing

app_createAccount:
    path:    /create_account
    defaults:
        _controller: AppBundle:Site:createAccount

app_showAccount:
    path:    /show_account{id}
    defaults:
        _controller: AppBundle:Site:showAccount
    requirements:
        id: \d+

#Advert routing
app_viewAd:
    path:    /Ad/{id}
    defaults:
        _controller: AppBundle:Site:viewAd
    requirements:
        id: \d+

app_newAd:
    path:    /new_Ad
    defaults:
        _controller: AppBundle:Site:newAd

app_editAd:
    path:    /edit_Ad/{id}
    defaults:
        _controller: AppBundle:Site:editAd
    requirements:
        id: \d+

app_deleteAd:
    path:    /delete_Ad/{id}
    defaults:
        _controller: AppBundle:Site:deleteAd
    requirements:
        id: \d+
