app_homepage:
    path:    /
    defaults:
        _controller: AppBundle:Site:index


#Account routing
app_createAccount:
    path:    /create_account
    defaults:
        _controller: AppBundle:Site:CreateAccount

app_showAccount:
    path:    /show_account
    defaults:
        _controller: AppBundle:Site:ShowAccount


#Addvert routing
app_viewAdd:
    path:    /add/{id}
    defaults:
        _controller: AppBundle:Site:ViewAdd
    requirements:
        id: \d+

app_newAdd:
    path:    /new_add
    defaults:
        _controller: AppBundle:Site:NewAdd

app_editAdd:
    path:    /edit_add/{id}
    defaults:
        _controller: AppBundle:Site:EditAdd
    requirements:
        id: \d+

app_deleteAdd:
    path:    /delete_add/{id}
    defaults:
        _controller: AppBundle:Site:DeleteAdd
    requirements:
        id: \d+
